dns:
  listen:
    port: 53
  servers:
    udp:
      address: 119.29.29.29
      port: 53
    http:
      url: https://public.diego.run/dns-query
      url_backup: https://dns.aliyun/com/dns-query
  mod: 1
  domain:
    gfwPath: domain/gfw.txt
    cnPath: domain/gfw.txt
