server:
  port: 8080
spring:
  profiles:
    active: dev


dns:
  listen:
    port: 8053
  servers:
    udp:
      address: 127.0.0.1
      port: 53
    http:
      url: https://dns.diego.org.cn/dns-query
      url_backup: https://dns.aliyun/com/dns-query
  mod: 1
  domain:
    gfwPath: /domain/gfw.txt
    cnPath: /domain/gfw.txt
