filePath:
  gfw-list: './domain/gfw.txt'
  cn-list: './domain/cn.txt'



dns:
  listen:
    port: 53
  servers:
    udp:
      address: 114.114.114.114
      port: 53
    http:
      url: https://dns.diego.run/dns-query
      url_backup: https://dns.aliyun/com/dns-query
  mod: 1
  domain:
    gfwPath: /domain/gfw.txt
    cnPath: /domain/gfw.txt