server:
  port: 8081
spring:
  profiles:
    active: dev


dns:
  listen:
    port: 8053
  servers:
    udp:
      address: 223.5.5.5
      port: 53
    http:
      url: https://dns.diego.org.cn/dns-query
  mod: 1
  domain:
    gfwPath: ./domain/gfw.txt
    cnPath: ./domain/gfw.txt
